#!/usr/bin/env bash
# processors/stub/run.sh
# Stub processor for end-to-end testing.
# Honors the Knowledge Builder §8 Processor Contract exactly.
#
# Usage: <JSON on stdin> | run.sh <input_path> <work_dir>
#
# Input  (stdin): JSON ProcessorInput object
# Output (stdout): log lines followed by a final JSON line on the LAST line
# Exit code: 0 on success

set -euo pipefail

# ── 1. Read full stdin into a variable ───────────────────────────────────────
INPUT_JSON="$(cat)"

# ── 2. Extract fields from JSON ───────────────────────────────────────────────
# Try jq first; fall back to Python if jq is not installed.
if command -v jq >/dev/null 2>&1; then
    INPUT_PATH="$(  printf '%s' "$INPUT_JSON" | jq -r '.input_path')"
    VAULT_ROOT="$(  printf '%s' "$INPUT_JSON" | jq -r '.vault_root')"
    SOURCES_DIR="$( printf '%s' "$INPUT_JSON" | jq -r '.sources_dir')"
    WORK_DIR="$(    printf '%s' "$INPUT_JSON" | jq -r '.work_dir')"
    CONTENT_HASH="$(printf '%s' "$INPUT_JSON" | jq -r '.content_hash')"
    JOB_ID="$(      printf '%s' "$INPUT_JSON" | jq -r '.job_id')"
    ATTEMPT="$(     printf '%s' "$INPUT_JSON" | jq -r '.attempt')"
else
    # Python one-liner fallback (Python 3 required)
    _py() { python3 -c "import sys,json; d=json.load(sys.stdin); print(d['$1'])" <<< "$INPUT_JSON"; }
    INPUT_PATH="$(_py input_path)"
    VAULT_ROOT="$(_py vault_root)"
    SOURCES_DIR="$(_py sources_dir)"
    WORK_DIR="$(   _py work_dir)"
    CONTENT_HASH="$(_py content_hash)"
    JOB_ID="$(     _py job_id)"
    ATTEMPT="$(    _py attempt)"
fi

# ── 3. Log lines (parser must find the LAST line as JSON) ────────────────────
echo "[stub] job_id=${JOB_ID} attempt=${ATTEMPT}"
echo "[stub] input_path=${INPUT_PATH}"
echo "[stub] vault_root=${VAULT_ROOT}"
echo "[stub] sources_dir=${SOURCES_DIR}"
echo "[stub] work_dir=${WORK_DIR}"
echo "[stub] content_hash=${CONTENT_HASH}"

# ── 4. Derive output path ─────────────────────────────────────────────────────
BASENAME="$(basename "${INPUT_PATH}")"
FILENAME="${BASENAME}"
NOTES_DIR="${VAULT_ROOT}/Notes"
OUTPUT_PATH="${NOTES_DIR}/${BASENAME%.}.md"

# Strip any existing extension and append .md
STEM="${BASENAME%.*}"
OUTPUT_PATH="${NOTES_DIR}/${STEM}.md"

echo "[stub] output_path=${OUTPUT_PATH}"

# ── 5. Create Notes/ directory if needed ─────────────────────────────────────
mkdir -p "${NOTES_DIR}"

# ── 6. Create work_dir if needed ─────────────────────────────────────────────
mkdir -p "${WORK_DIR}"

# ── 7. Write output atomically (temp → mv) ───────────────────────────────────
TEMP_FILE="$(mktemp "${WORK_DIR}/stub_output.XXXXXX")"

cat > "${TEMP_FILE}" <<EOF
# Processed: ${FILENAME}

Source: ${INPUT_PATH}
Hash: ${CONTENT_HASH}

> This file was generated by the stub processor for testing purposes.
> Job ID: ${JOB_ID}  Attempt: ${ATTEMPT}
EOF

mv "${TEMP_FILE}" "${OUTPUT_PATH}"

echo "[stub] wrote output atomically via temp=${TEMP_FILE}"

# ── 8. Compute output size ────────────────────────────────────────────────────
if command -v stat >/dev/null 2>&1; then
    # macOS stat uses -f %z; GNU stat uses -c %s
    if stat -f %z "${OUTPUT_PATH}" >/dev/null 2>&1; then
        OUTPUT_BYTES="$(stat -f %z "${OUTPUT_PATH}")"
    else
        OUTPUT_BYTES="$(stat -c %s "${OUTPUT_PATH}")"
    fi
else
    OUTPUT_BYTES="$(wc -c < "${OUTPUT_PATH}" | tr -d ' ')"
fi

echo "[stub] output_bytes=${OUTPUT_BYTES}"

# ── 9. Emit final JSON on the LAST line ───────────────────────────────────────
# IMPORTANT: This MUST be the last line of stdout.
printf '{"status":"ok","outputs":[{"path":"%s","kind":"markdown","bytes":%s}],"metadata":{"processor":"stub","version":"0.1"}}\n' \
    "${OUTPUT_PATH}" "${OUTPUT_BYTES}"
